id: P002935
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25371
  title: དཔལ་འབྱོར་རིག་པའི་གཞིག་སྟངས།
  author: ''
  volumes:
    3252f9fc2ec14970af63fbc012320625:
      image_group_id: I1KG25373
      title: ''
      volume_number: 1
      total_pages: 392
      base_file: v001.txt
